### PR TITLE
Fixes #12304 - Support older ruby versions for array to hash in facter

### PR DESCRIPTION
**Pull request by shlomizadok**
Tested with Rubies: 1.8.5, 1.9.3, 2.0.0, 2.1.0

### CODE REVIEW

**Comment by shlomizadok** [comment]
@ares - can you please take a look?

**Comment by shlomizadok** [comment]
@ohadlevy, @domcleal - mind taking a look?

**Comment by dLobatog** [comment]
:+1: works well on 1.9.3, 2.0.0, 2.1.0 and 1.8.7. I can't test it on 1.8.5 right now, `rbenv` doesn't offer the option.

**Comment by ohadlevy** [comment]
I didnt run it across 1.8.5 either but it does look sane assumed you tested on it.

**Comment by shlomizadok** [comment]
Merging. Thanks @ohadlevy & @dLobatog for testing (I've tested w/ 1.8.5)

**Pull request merged**
