### PR TITLE
fix #10007 - ensure /etc/foreman_scap_client directory

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by isimluk** [comment]
Why this is needed?

**Comment by shlomizadok** [comment]
See [#10007](http://projects.theforeman.org/issues/10007)
It seems that the directory is not created on CentOS (possibly also not created on Fedora).
This ensures that the directory is created, else the config.yaml creation will fail.

**Comment by isimluk** [comment]
This is weird. Did you investigate why this is happening?

This directory should be already created by foreman_scap_client.rpm package. If possible, I would like to avoid code duplication.

**Comment by shlomizadok** [comment]
in https://github.com/theforeman/foreman-packaging/blob/rpm/develop/rubygem-foreman_scap_client/rubygem-foreman_scap_client.spec#L71 is %{buildroot} == /etc ?

**Comment by shlomizadok** [comment]
closed under protest :)

**Pull request closed without merging**
