### PR TITLE
Fixes #14158 - Add support for tailoring file

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Also please update the documentation in README.md and init.pp

**Comment by xprazak2** [comment]
Updated.

**Comment by ares** [comment]
Ok, this will work with older foreman_openscap too but in general should be used with upcoming release (0.7.0) I guess. We should probably bump the module to 0.4 once this is in.

**Review by ares — APPROVED** [review]

**Comment by shlomizadok** [comment]
Thanks @xprazak2 !!

**Pull request merged**
